<?php

/**
 * Model_ExampleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ExampleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ExampleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Example');
    }
}